local map = require('utils')
local dap = require('dap')

map.leaderNmap('b', dap.toggle_breakpoint, "Toggle [b]reakpoint")
map.leaderNmap('Dc', dap.continue, "[c]ontinue")
map.leaderNmap('Dso', dap.step_over, "[o]ver")
map.leaderNmap('Dsi', dap.step_into, "[i]nto")
map.leaderNmap('Dr', dap.restart, "[r]estart")
map.leaderNmap('Dq', dap.terminate, "[q]uit")
map.leaderNmap('DC', dap.clear_breakpoints, "[C]lear Breakpoints")
