local map = require('utils')
local dap = require('dap')

map.leader_nmap('b', dap.toggle_breakpoint, "Toggle [b]reakpoint")
map.leader_nmap('Dc', dap.continue, "[c]ontinue")
map.leader_nmap('Dso', dap.step_over, "[o]ver")
map.leader_nmap('Dsi', dap.step_into, "[i]nto")
map.leader_nmap('Dr', dap.restart, "[r]estart")
map.leader_nmap('Dq', dap.terminate, "[q]uit")
map.leader_nmap('DC', dap.clear_breakpoints, "[C]lear Breakpoints")
